#!/bin/sh


FILES="
vimrc:$HOME/.vimrc
"


main()
{
    base_dir="$PWD"
    delete=no

    parse_arguments "$@"

    if [ $delete = no ]
    then
        setup
    else
        delete
    fi
}


parse_arguments()
{
    while [ "$#" -gt 0 ]
    do
        case $1 in
            -d | --delete)
                delete=yes
                shift
                ;;
            -h | --help)
                show_help
                exit
                ;;
            -?*)
                quit Unknown option \""$1"\".
                ;;
            *)
                quit Surplus argument \""$1"\".
                ;;
        esac
    done
}


setup()
{
    printf "%s" "$FILES" | grep [[:graph:]] | while read line
    do
        src=$(printf "%s" "$line" | cut -d: -f1)
        src="$base_dir/$src"
        dst=$(printf "%s" "$line" | cut -d: -f2)

        if [ ! -f "$src" ]
        then
            printf "%s\n" "Error: File $src does not exist"
            continue
        fi

        if ln -s "$src" "$dst"
        then
            printf "%s\n" "Created $dst -> $src"
        else
            printf "%s\n" "Error: Failed to create $dst -> $src"
        fi
    done
}


delete()
{
    printf "%s" "$FILES" | grep [[:graph:]] | while read line
    do
        dst=$(printf "%s" "$line" | cut -d: -f2)
        if rm "$dst"
        then
            printf "%s\n" "Deleted $dst"
        else
            printf "%s\n" "Error: Failed to delete $dst"
        fi
    done
}


show_help()
{
    printf "Usage: $0 [-d] [-h]

Setup files in home directory.

Options:
  -d, --delete  Delete files. 
  -h, --help    Show this help and exit.
"
}


main "$@"
