#!/bin/sh


DOT_FILES="
vimrc
tmux.conf
"


main()
{
    [ $# -gt 1 ] && quit Surplus argument \""$2"\"
    [ $# -eq 0 ] && arg='<default>' || arg=$1

    case $arg in
        '<default>')
            undo_all
            setup_all
            ;;
        rm)
            undo_all
            ;;
        help | -h | --help)
            show_help
            ;;
        *)
            quit Unknown argument \""$1"\"
            ;;
    esac
}


setup_all()
{
    log Installing setup ...
    setup_dot_files
    setup_shrc
    setup_git_config
    log
}


undo_all()
{
    log Removing setup ...
    undo_dot_files
    undo_shrc
    undo_git_config
    log
}


setup_dot_files()
{
    printf "%s" "$DOT_FILES" | grep [[:graph:]] | while read filename
    do
        target="$PWD/_$filename"
        link=~/."$filename"

        if [ -f "$link" ]
        then
            err Link "$link" already exists
        elif [ ! -f "$target" ]
        then
            err File "$target" does not exist
        elif ln -s "$target" "$link"
        then
            log Created "$link -> $target"
        fi
    done
}


undo_dot_files()
{
    printf "%s" "$DOT_FILES" | grep [[:graph:]] | while read filename
    do
        link=~/."$filename"
        if [ ! -f "$link" ]
        then
            err Link "$link" does not exist
        elif rm "$link"
        then
            log Deleted "$link"
        fi
    done
}


# Comment to mark lines inserted by this script.
SETUP_MARK='# Added by setup script'


setup_shrc()
{
    shrc="$PWD/shrc"
    cmd="[ -f \"$shrc\" ] && . \"$shrc\" $SETUP_MARK"

    for file in ~/.bashrc ~/.bash_profile ~/.zshrc
    do
    if [ -f "$file" ]
    then
        if grep -q "$SETUP_MARK" "$file"
        then
        err File "$file" is already updated to load shrc
        elif echo "$cmd" >> "$file"
        then
        log Updated "$file" to load shrc
        fi
    else
        log Ignored missing file "$file". \
            To setup "$file", create it manually and run setup again.
    fi
    done
    unset shrc
    unset cmd
    unset file
}


undo_shrc()
{
    for file in ~/.bashrc ~/.bash_profile ~/.zshrc
    do
        if [ -f "$file" ]
        then
            if grep -q "$SETUP_MARK" "$file"
            then
                sed "/$SETUP_MARK/d" "$file" > "$file.tmp" &&
                mv "$file.tmp" "$file" &&
                log File "$file" updated to not load shrc
            else
                err File "$file" does not load shrc
            fi
        else
            err Ignored missing file "$file"
        fi
    done
    unset file
}


setup_git_config()
{
    sh -x ./gitconfig.sh
}


undo_git_config()
{
    awk '/^git/ {print $1 " " $2 " " $3 " --unset " $4}' gitconfig.sh | sh -x
}


err()
{
    log "$0: $*"
}


log()
{
    printf "%s\n" "$*" >&2
}


quit()
{
    err "$*"
    exit 1
}


show_help()
{
    printf "Usage: $0 [rm | help]

Setup files in home directory.

Actions:
  <default>  Reinstall setup if no action is specified.
  rm         Remove setup.
  help       Show this help and exit.
"
}


main "$@"
